--------------------------------------------------------
--  File created - Tuesday-December-15-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AA_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AA_CUSTOMER" 
   (	"ID" NUMBER, 
	"FNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"ADDRESS" LONG, 
	"TEL" VARCHAR2(11 BYTE), 
	"BIRTHDAY" DATE, 
	"GENDER" VARCHAR2(20 BYTE), 
	"E_MAIL" VARCHAR2(40 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ACCOUNT_ADMIN" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AA_CUSTOMER
SET DEFINE OFF;
Insert into SYSTEM.AA_CUSTOMER (ID,FNAME,LNAME,ADDRESS,TEL,BIRTHDAY,GENDER,E_MAIL,USERNAME,PASSWORD,ACCOUNT_ADMIN) values (549,'กรวิชญ์','ปีติเวช','429 ถ.ซูปเปอร์ไฮเวย์เชียงใหม่-ลำปาง ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50000','085-6498236',to_date('20-DEC-96','DD-MON-RR'),'ชาย','abc@outlook.com','kar','1234',1);
Insert into SYSTEM.AA_CUSTOMER (ID,FNAME,LNAME,ADDRESS,TEL,BIRTHDAY,GENDER,E_MAIL,USERNAME,PASSWORD,ACCOUNT_ADMIN) values (550,'ปีเตอร์','ธนัช','55 ถ.ห้วยแก้ว ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200','089-5642198',to_date('16-DEC-91','DD-MON-RR'),'ชาย','atapunpy@hotmail.com','Peter ','1235',0);
Insert into SYSTEM.AA_CUSTOMER (ID,FNAME,LNAME,ADDRESS,TEL,BIRTHDAY,GENDER,E_MAIL,USERNAME,PASSWORD,ACCOUNT_ADMIN) values (551,'เฟลิเซีย','เปศล','169 หมู่ 3 ตำบลหนองแก้ว อำเภอหางดง จังหวัดเชียงใหม่ 50230','098-8887999',to_date('30-DEC-93','DD-MON-RR'),'หญิง','love33@icloud.com','Felicia','1236',0);
Insert into SYSTEM.AA_CUSTOMER (ID,FNAME,LNAME,ADDRESS,TEL,BIRTHDAY,GENDER,E_MAIL,USERNAME,PASSWORD,ACCOUNT_ADMIN) values (552,'ฟลอเรนซ์','สุวีรา','78 ถ.ห้วยแก้ว ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200','089-2665256',to_date('01-DEC-15','DD-MON-RR'),'หญิง','yyy@outlook.com','Florence','1237',0);
Insert into SYSTEM.AA_CUSTOMER (ID,FNAME,LNAME,ADDRESS,TEL,BIRTHDAY,GENDER,E_MAIL,USERNAME,PASSWORD,ACCOUNT_ADMIN) values (553,'แคทเธอรีน','ปัจจรี','202 ถนนช้างเผือก อำเภอเมือง จังหวัดเชียงใหม่ 50300','085-9874444',to_date('29-DEC-92','DD-MON-RR'),'หญิง','aaa@icloud.com','Catherine','1238',0);
--------------------------------------------------------
--  DDL for Index AA_DETEILCUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AA_DETEILCUSTOMER_PK" ON "SYSTEM"."AA_CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AA_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AA_CUSTOMER" ADD CONSTRAINT "AA_DETEILCUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("ACCOUNT_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("E_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
