--------------------------------------------------------
--  File created - Tuesday-December-15-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AA_EACHBOOK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AA_EACHBOOK" 
   (	"ID" NUMBER, 
	"STATUSBOOK" VARCHAR2(10 BYTE), 
	"STATISTICBOOK" NUMBER, 
	"ISBN" VARCHAR2(17 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AA_EACHBOOK
SET DEFINE OFF;
Insert into SYSTEM.AA_EACHBOOK (ID,STATUSBOOK,STATISTICBOOK,ISBN) values (11,'1',5,'9875268444');
Insert into SYSTEM.AA_EACHBOOK (ID,STATUSBOOK,STATISTICBOOK,ISBN) values (12,'1',2,'7965213648');
Insert into SYSTEM.AA_EACHBOOK (ID,STATUSBOOK,STATISTICBOOK,ISBN) values (13,'1',7,'5847456985');
Insert into SYSTEM.AA_EACHBOOK (ID,STATUSBOOK,STATISTICBOOK,ISBN) values (14,'1',8,'4569773216');
Insert into SYSTEM.AA_EACHBOOK (ID,STATUSBOOK,STATISTICBOOK,ISBN) values (15,'1',4,'4589685872');
--------------------------------------------------------
--  DDL for Index AA_EACHBOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AA_EACHBOOK_PK" ON "SYSTEM"."AA_EACHBOOK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AA_EACHBOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AA_EACHBOOK" ADD CONSTRAINT "AA_EACHBOOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."AA_EACHBOOK" MODIFY ("STATUSBOOK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AA_EACHBOOK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AA_EACHBOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AA_EACHBOOK" ADD CONSTRAINT "AA_EACHBOOK_FK1" FOREIGN KEY ("ISBN")
	  REFERENCES "SYSTEM"."AA_BOOK" ("ISBN") ENABLE;
