DROP TABLE AA_BOOK  CASCADE CONSTRAINTS;
CREATE TABLE AA_BOOK 
(
  ISBN VARCHAR2(17 BYTE) NOT NULL 
, BOOKNAME VARCHAR2(100 BYTE) 
, PRICERENT NUMBER 
, TOTAL NUMBER 
, REMAIN NUMBER 
, ID_TYPE NUMBER 
, ID_COMPANY NUMBER 
, WRITER VARCHAR2(200 BYTE) 
, NUM_PAGE NUMBER 
, DETAIL LONG 
, DATE_ADD DATE 
, CONSTRAINT AA_BOOK_PK PRIMARY KEY 
  (
    ISBN 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_BOOK_PK ON AA_BOOK (ISBN ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE AA_BOOK
ADD CONSTRAINT AA_BOOK_FK1 FOREIGN KEY
(
  ID_TYPE 
)
REFERENCES AA_TYPEBOOK
(
  ID_TYPE 
)
ENABLE;

ALTER TABLE AA_BOOK
ADD CONSTRAINT AA_BOOK_FK2 FOREIGN KEY
(
  ID_COMPANY 
)
REFERENCES AA_COMPANY
(
  ID_COMPANY 
)
ENABLE;





DROP TABLE AA_COMPANY CASCADE CONSTRAINTS;
CREATE TABLE AA_COMPANY 
(
  ID_COMPANY NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) NOT NULL 
, PHONE VARCHAR2(11 BYTE) 
, ADDRESS VARCHAR2(300 BYTE) 
, CONSTRAINT AA_COMPANY_PK PRIMARY KEY 
  (
    ID_COMPANY 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_COMPANY_PK ON AA_COMPANY (ID_COMPANY ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;





DROP TABLE AA_CUSTOMER  CASCADE CONSTRAINTS;
CREATE TABLE AA_CUSTOMER 
(
  ID NUMBER NOT NULL 
, FNAME VARCHAR2(30 BYTE) NOT NULL 
, LNAME VARCHAR2(30 BYTE) NOT NULL 
, ADDRESS LONG 
, TEL VARCHAR2(11 BYTE) NOT NULL 
, BIRTHDAY DATE NOT NULL 
, GENDER VARCHAR2(6 BYTE) NOT NULL 
, E_MAIL VARCHAR2(40 BYTE) NOT NULL 
, USERNAME VARCHAR2(30 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
, ACCOUNT_ADMIN NUMBER(1, 0) NOT NULL 
, CONSTRAINT AA_DETEILCUSTOMER_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_DETEILCUSTOMER_PK ON AA_CUSTOMER (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;




DROP TABLE AA_EACHBOOK   CASCADE CONSTRAINTS;
CREATE TABLE AA_EACHBOOK 
(
  ID NUMBER NOT NULL 
, STATUSBOOK VARCHAR2(10 BYTE) NOT NULL 
, STATISTICBOOK NUMBER 
, ISBN VARCHAR2(17 BYTE) 
, CONSTRAINT AA_EACHBOOK_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_EACHBOOK_PK ON AA_EACHBOOK (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE AA_EACHBOOK
ADD CONSTRAINT AA_EACHBOOK_FK1 FOREIGN KEY
(
  ISBN 
)
REFERENCES AA_BOOK
(
  ISBN 
)
ENABLE;





DROP TABLE AA_RENT   CASCADE CONSTRAINTS;
CREATE TABLE AA_RENT 
(
  ID NUMBER NOT NULL 
, START_RENT DATE 
, END_RENT DATE 
, ISBN VARCHAR2(17 BYTE) 
, ID_EBOOK NUMBER 
, ID_CUSTOMER NUMBER 
, CONSTRAINT AA_RENT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_RENT_PK ON AA_RENT (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE AA_RENT
ADD CONSTRAINT AA_RENT_FK1 FOREIGN KEY
(
  ID_EBOOK 
)
REFERENCES AA_EACHBOOK
(
  ID 
)
ENABLE;

ALTER TABLE AA_RENT
ADD CONSTRAINT AA_RENT_FK2 FOREIGN KEY
(
  ID_CUSTOMER 
)
REFERENCES AA_CUSTOMER
(
  ID 
)
ENABLE;

ALTER TABLE AA_RENT
ADD CONSTRAINT AA_RENT_FK3 FOREIGN KEY
(
  ISBN 
)
REFERENCES AA_BOOK
(
  ISBN 
)
ENABLE;




DROP TABLE AA_TYPEBOOK    CASCADE CONSTRAINTS;
CREATE TABLE AA_TYPEBOOK 
(
  ID_TYPE NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, CONSTRAINT AA_TYPEBOOK_PK PRIMARY KEY 
  (
    ID_TYPE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX AA_TYPEBOOK_PK ON AA_TYPEBOOK (ID_TYPE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
DROP SEQUENCE type_book_seq  ;
DROP SEQUENCE id_rent_seq  ;
DROP SEQUENCE id_eachbook_seq  ;
DROP SEQUENCE id_company_seq  ;
CREATE SEQUENCE type_book_seq START with 1 INCREMENT BY 1;
CREATE SEQUENCE id_rent_seq START with 1 INCREMENT BY 1;
CREATE SEQUENCE id_eachbook_seq START with 1 INCREMENT BY 1;
CREATE SEQUENCE id_company_seq START with 1 INCREMENT BY 1;