--------------------------------------------------------
--  DDL for Table AA_RENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AA_RENT" 
   (	"ID" NUMBER, 
	"START_RENT" DATE, 
	"END_RENT" DATE, 
	"ISBN" NUMBER, 
	"ID_EBOOK" NUMBER, 
	"ID_CUSTOMER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
